use super::super::{AppError, DuckCrudModel, SurrealCrudModel, ToPolars};
use duckdb::Connection;
use polars::prelude::*;
use serde::{Deserialize, Serialize};
use std::path::Path;
use std::sync::{Arc, Mutex};

#[allow(non_snake_case)]
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FullBankData {
    pub year: Option<f64>,
    pub entity: Option<f64>,
    pub exec_fullname_comp: Option<String>,
    pub coname: Option<String>,
    pub directorid: Option<f64>,
    pub conglomerate_exp: Option<f64>,
    pub count_industries: Option<f64>,
    pub ceo_exp_dummy: Option<f64>,
    pub Countpastpositions: Option<f64>,
    pub Countpastfirms: Option<f64>,
    pub gvkey: Option<f64>,
    pub companyid: Option<f64>,
    pub titleann: Option<String>,
    pub execid: Option<f64>,
    pub port_delta: Option<f64>,
    pub port_vega: Option<f64>,
    pub port_value: Option<f64>,
    pub shrown_excl_opts: Option<f64>,
    pub quarter: Option<f64>,
    pub co_per_rol: Option<f64>,
    pub name: Option<String>,
    pub month: Option<f64>,
    pub day: Option<f64>,
    pub year_quarter: Option<f64>,
    pub inst_type: Option<String>,
    pub LCO: Option<f64>,
    pub LLP: Option<f64>,
    pub IntRateSwps_HTM: Option<f64>,
    pub RWA: Option<f64>,
    pub Loans: Option<f64>,
    pub cash: Option<f64>,
    pub Retained_Earnings: Option<f64>,
    pub NPL: Option<f64>,
    pub CL_NPL: Option<f64>,
    pub MO_NPL: Option<f64>,
    pub OTHER_NPL: Option<f64>,
    pub Loangrowth: Option<f64>,
    pub Ebllp_Loans_t_1: Option<f64>,
    pub LLP_Loans_t_1: Option<f64>,
    pub TA: Option<f64>,
    pub log_TA: Option<f64>,
    pub TL: Option<f64>,
    pub TE: Option<f64>,
    pub Leverage: Option<f64>,
    pub Tier1Capital: Option<f64>,
    pub CA: Option<f64>,
    pub ROA_t_1: Option<f64>,
    pub ROE_t_1: Option<f64>,
    pub Loans_TA: Option<f64>,
    pub Trading_Income_TRA: Option<f64>,
    pub CL: Option<f64>,
    pub EBIT: Option<f64>,
    pub NetIncome: Option<f64>,
    pub InterestInc: Option<f64>,
    pub NonInterestInc: Option<f64>,
    pub OI: Option<f64>,
    pub NonInterestInc_TA: Option<f64>,
    pub Trading_Income: Option<f64>,
    pub DSC: Option<f64>,
    pub TOTAL_Expenses: Option<f64>,
    pub Interest_Expenses: Option<f64>,
    pub Non_Interest_Expenses: Option<f64>,
    pub Interest_Expenses_TE: Option<f64>,
    pub Net_InterestInc: Option<f64>,
    pub Net_NonInterestInc: Option<f64>,
    pub Net_NonInterestInc_OI: Option<f64>,
    pub Net_InterestInc_OI: Option<f64>,
    pub InterestInc_TA: Option<f64>,
    pub Trading_Assets: Option<f64>,
    pub Trading_Income_TA: Option<f64>,
    pub IntRateSwps: Option<f64>,
    pub IntRateSwps_TA: Option<f64>,
    pub Income: Option<f64>,
    pub Trading_Income_TR: Option<f64>,
    pub Non_Interest_Expenses_TE: Option<f64>,
    pub fee_mix: Option<f64>,
    pub rev_mix: Option<f64>,
    pub InterestInc_Inc: Option<f64>,
    pub Working_Capital: Option<f64>,
    pub RetEarnings_TA: Option<f64>,
    pub EBIT_TA: Option<f64>,
    pub OI_TA: Option<f64>,
    pub Working_Capital_TA: Option<f64>,
    pub Trading_Assets_TA: Option<f64>,
    pub mismatch: Option<f64>,
    pub revolver: Option<f64>,
    pub CILOANS: Option<f64>,
    pub CONLOANS: Option<f64>,
    pub TLMI: Option<f64>,
    pub Forfxfut: Option<f64>,
    pub ROA: Option<f64>,
    pub ROE: Option<f64>,
    pub NII: Option<f64>,
    pub Other_NIE: Option<f64>,
    pub Other_IE: Option<f64>,
    pub Net_Repos: Option<f64>,
    pub Commercial_Paper: Option<f64>,
    pub brokered_dep: Option<f64>,
    pub stdebt: Option<f64>,
    pub Treas_sec: Option<f64>,
    pub Net_FedFunds: Option<f64>,
    pub SubNotesDebt: Option<f64>,
    pub Other_Debt: Option<f64>,
    pub htm_tot_secur: Option<f64>,
    pub htm_tot_secur2: Option<f64>,
    pub avfs_tot_secur: Option<f64>,
    pub fv_htm_dom_debt_sec: Option<f64>,
    pub fv_htm_for_debt_sec: Option<f64>,
    pub ammor_htm_dom_debt_sec: Option<f64>,
    pub ammor_htm_for_debt_sec: Option<f64>,
    pub fv_htm_tot_sec: Option<f64>,
    pub ammor_htm_tot_sec: Option<f64>,
    pub htm_tot_secur_TA: Option<f64>,
    pub htm_tot_secur2_TA: Option<f64>,
    pub avfs_tot_secur_TA: Option<f64>,
    pub fv_htm_dom_debt_sec_TA: Option<f64>,
    pub fv_htm_for_debt_sec_TA: Option<f64>,
    pub ammor_htm_dom_debt_sec_TA: Option<f64>,
    pub ammor_htm_for_debt_sec_TA: Option<f64>,
    pub fv_htm_tot_sec_TA: Option<f64>,
    pub ammor_htm_tot_sec_TA: Option<f64>,
    pub MOLOANS: Option<f64>,
    pub RELOANS: Option<f64>,
    pub OTHERLOANS: Option<f64>,
    pub Deposits: Option<f64>,
    pub GAP12: Option<f64>,
    pub FCA: Option<f64>,
    pub FED: Option<f64>,
    pub FXRD: Option<f64>,
    pub ERD: Option<f64>,
    pub CreditPS: Option<f64>,
    pub CreditPB: Option<f64>,
    pub NetCreditPB: Option<f64>,
    pub TotBorrowing: Option<f64>,
    pub Tier1Capital_Ratio: Option<f64>,
    pub NPL_Ratio: Option<f64>,
    pub NonInterestInc_TA_mean_high: Option<f64>,
    pub NonInterestInc_TA_med_high: Option<f64>,
    pub NonInterestInc_TA_mean: Option<f64>,
    pub NonInterestInc_TA_median: Option<f64>,
    pub InterestInc_TA_mean_high: Option<f64>,
    pub InterestInc_TA_med_high: Option<f64>,
    pub InterestInc_TA_mean: Option<f64>,
    pub InterestInc_TA_median: Option<f64>,
    pub InterestInc_Inc_mean_high: Option<f64>,
    pub InterestInc_Inc_med_high: Option<f64>,
    pub InterestInc_Inc_mean: Option<f64>,
    pub InterestInc_Inc_median: Option<f64>,
    pub abs_Delta_ROA_lead: Option<f64>,
    pub Delta_ROA_lead: Option<f64>,
    pub Delta_InterestInc_TA_lead: Option<f64>,
    pub abs_Delta_InterestInc_TA_lead: Option<f64>,
    pub Delta_NonInterestInc_TA_lead: Option<f64>,
    pub abs_Delta_NonInterestInc_TA_lead: Option<f64>,
    pub Deposits_TA: Option<f64>,
    pub log_Asset_Growth: Option<f64>,
    pub abs_Delta_ROE_lead: Option<f64>,
    pub Delta_NPL_Ratio_lead: Option<f64>,
    pub abs_Delta_NPL_Ratio_lead: Option<f64>,
    pub Delta_Leverage_lead: Option<f64>,
    pub abs_Delta_Leverage_lead: Option<f64>,
    pub Delta_ROE_lead: Option<f64>,
    pub Delta_LLP_Loans_t_1_lead: Option<f64>,
    pub abs_Delta_LLP_Loans_t_1_lead: Option<f64>,
    pub ROA_mean: Option<f64>,
    pub ROA_median: Option<f64>,
    pub ROA_mean_high: Option<f64>,
    pub ROA_med_high: Option<f64>,
    pub ROE_mean: Option<f64>,
    pub ROE_median: Option<f64>,
    pub ROE_mean_high: Option<f64>,
    pub ROE_med_high: Option<f64>,
    pub TA_mean: Option<f64>,
    pub TA_median: Option<f64>,
    pub TA_mean_high: Option<f64>,
    pub TA_med_high: Option<f64>,
    pub fee_mix_mean: Option<f64>,
    pub fee_mix_median: Option<f64>,
    pub fee_mix_mean_high: Option<f64>,
    pub fee_mix_med_high: Option<f64>,
    pub rev_mix_mean: Option<f64>,
    pub rev_mix_median: Option<f64>,
    pub rev_mix_mean_high: Option<f64>,
    pub rev_mix_med_high: Option<f64>,
    pub Deposits_TA_mean: Option<f64>,
    pub Deposits_TA_median: Option<f64>,
    pub Deposits_TA_mean_high: Option<f64>,
    pub Deposits_TA_med_high: Option<f64>,
    pub log_Asset_Growth_mean: Option<f64>,
    pub log_Asset_Growth_median: Option<f64>,
    pub log_Asset_Growth_mean_high: Option<f64>,
    pub log_Asset_Growth_med_high: Option<f64>,
    pub RWA_TA: Option<f64>,
    pub Trading_Assets_TA_mean_high: Option<f64>,
    pub Trading_Assets_TA_med_high: Option<f64>,
    pub Trading_Assets_TA_mean: Option<f64>,
    pub Trading_Assets_TA_median: Option<f64>,
    pub Trading_Assets_Dummy: Option<f64>,
    pub Trading_Income_TA_mean_high: Option<f64>,
    pub Trading_Income_TA_med_high: Option<f64>,
    pub Trading_Income_TA_mean: Option<f64>,
    pub Trading_Income_TA_median: Option<f64>,
    pub Trading_Income_TR_mean_high: Option<f64>,
    pub Trading_Income_TR_med_high: Option<f64>,
    pub Trading_Income_TR_mean: Option<f64>,
    pub Trading_Income_TR_median: Option<f64>,
    pub Trading_Income_TRA_mean_high: Option<f64>,
    pub Trading_Income_TRA_med_high: Option<f64>,
    pub Trading_Income_TRA_mean: Option<f64>,
    pub Trading_Income_TRA_median: Option<f64>,
    pub abs_Delta_Loans_lead: Option<f64>,
    pub Delta_Loans_lead: Option<f64>,
    pub abs_Delta_Loans_lead_perc: Option<f64>,
    pub Delta_Loans_lead_perc: Option<f64>,
    pub abs_Delta_Deposits_lead: Option<f64>,
    pub Delta_Deposits_lead: Option<f64>,
    pub abs_Delta_Deposits_lead_perc: Option<f64>,
    pub Delta_Deposits_lead_perc: Option<f64>,
    pub abs_Delta_htm_tot_secur_lead: Option<f64>,
    pub Delta_htm_tot_secur_lead: Option<f64>,
    pub abs_Delta_htm_tot_secur_perc: Option<f64>,
    pub Delta_htm_tot_secur_lead_perc: Option<f64>,
    pub states_counts: Option<f64>,
    pub interstate_bank: Option<f64>,
    pub permco: Option<f64>,
    pub permno: Option<f64>,
    pub total_return: Option<f64>,
    pub adj_total_return: Option<f64>,
    pub conm: Option<String>,
    pub shrcls: Option<String>,
    pub vwretd_VAR1_yr: Option<f64>,
    pub ewretd_VAR1_yr: Option<f64>,
    pub vwretd_VAR5_yr: Option<f64>,
    pub ewretd_VAR5_yr: Option<f64>,
    pub vwretd_VAR1_qtr: Option<f64>,
    pub ewretd_VAR1_qtr: Option<f64>,
    pub vwretd_VAR5_qtr: Option<f64>,
    pub ewretd_VAR5_qtr: Option<f64>,
    pub ES1_ew_yr: Option<f64>,
    pub ES5_ew_yr: Option<f64>,
    pub ES1_ew_yr_t_1: Option<f64>,
    pub delta_ES1_ew_yr_lag: Option<f64>,
    pub delta_ES1_ew_yr_lead: Option<f64>,
    pub ES5_ew_yr_t_1: Option<f64>,
    pub delta_ES5_ew_yr_lag: Option<f64>,
    pub delta_ES5_ew_yr_lead: Option<f64>,
    pub vwretd_MES1_ew_yr: Option<f64>,
    pub ewretd_MES1_ew_yr: Option<f64>,
    pub vwretd_MES5_ew_yr: Option<f64>,
    pub ewretd_MES5_ew_yr: Option<f64>,
    pub vwretd_MES1_ew_yr_t_1: Option<f64>,
    pub delta_vwretd_MES1_ew_yr_lag: Option<f64>,
    pub delta_vwretd_MES1_ew_yr_lead: Option<f64>,
    pub ewretd_MES1_ew_yr_t_1: Option<f64>,
    pub delta_ewretd_MES1_ew_yr_lag: Option<f64>,
    pub delta_ewretd_MES1_ew_yr_lead: Option<f64>,
    pub vwretd_MES5_ew_yr_t_1: Option<f64>,
    pub delta_vwretd_MES5_ew_yr_lag: Option<f64>,
    pub delta_vwretd_MES5_ew_yr_lead: Option<f64>,
    pub ewretd_MES5_ew_yr_t_1: Option<f64>,
    pub delta_ewretd_MES5_ew_yr_lag: Option<f64>,
    pub delta_ewretd_MES5_ew_yr_lead: Option<f64>,
    pub ES1_ew_qtr: Option<f64>,
    pub ES5_ew_qtr: Option<f64>,
    pub ES1_ew_qtr_t_1: Option<f64>,
    pub ES1_ew_qtr_tp_1: Option<f64>,
    pub delta_ES1_ew_qtr_lag: Option<f64>,
    pub delta_ES1_ew_qtr_lead: Option<f64>,
    pub ES5_ew_qtr_t_1: Option<f64>,
    pub ES5_ew_qtr_tp_1: Option<f64>,
    pub delta_ES5_ew_qtr_lag: Option<f64>,
    pub delta_ES5_ew_qtr_lead: Option<f64>,
    pub vwretd_MES1_ew_qtr: Option<f64>,
    pub ewretd_MES1_ew_qtr: Option<f64>,
    pub vwretd_MES5_ew_qtr: Option<f64>,
    pub ewretd_MES5_ew_qtr: Option<f64>,
    pub vwretd_MES1_ew_qtr_t_1: Option<f64>,
    pub vwretd_MES1_ew_qtr_tp_1: Option<f64>,
    pub delta_vwretd_MES1_ew_qtr_lag: Option<f64>,
    pub delta_vwretd_MES1_ew_qtr_lead: Option<f64>,
    pub ewretd_MES1_ew_qtr_t_1: Option<f64>,
    pub ewretd_MES1_ew_qtr_tp_1: Option<f64>,
    pub delta_ewretd_MES1_ew_qtr_lag: Option<f64>,
    pub delta_ewretd_MES1_ew_qtr_lead: Option<f64>,
    pub vwretd_MES5_ew_qtr_t_1: Option<f64>,
    pub vwretd_MES5_ew_qtr_tp_1: Option<f64>,
    pub delta_vwretd_MES5_ew_qtr_lag: Option<f64>,
    pub delta_vwretd_MES5_ew_qtr_lead: Option<f64>,
    pub ewretd_MES5_ew_qtr_t_1: Option<f64>,
    pub ewretd_MES5_ew_qtr_tp_1: Option<f64>,
    pub delta_ewretd_MES5_ew_qtr_lag: Option<f64>,
    pub delta_ewretd_MES5_ew_qtr_lead: Option<f64>,
    pub sd_ret_q: Option<f64>,
    pub sd_ret_q_t_1: Option<f64>,
    pub sd_ret_q_tp_1: Option<f64>,
    pub delta_sd_ret_q_lag: Option<f64>,
    pub delta_sd_ret_q_lead: Option<f64>,
    pub sd_ret_yr: Option<f64>,
    pub sd_ret_yr_t_1: Option<f64>,
    pub delta_sd_ret_yr_lag: Option<f64>,
    pub delta_sd_ret_yr_lead: Option<f64>,
    pub ceoann: Option<String>,
    pub age: Option<f64>,
    pub tdc1: Option<f64>,
    pub bonus: Option<f64>,
    pub noneq_incent: Option<f64>,
    pub option_awards: Option<f64>,
    pub rstkgrnt: Option<f64>,
    pub othcomp: Option<f64>,
    pub shrown_tot: Option<f64>,
    pub opt_unex_exer_est_val: Option<f64>,
    pub opt_exer_val: Option<f64>,
    pub option_awards_blk_value: Option<f64>,
    pub opt_unex_unexer_est_val: Option<f64>,
    pub stock_unvest_val: Option<f64>,
    pub shares_owned: Option<f64>,
    pub excercisable_options: Option<f64>,
    pub unexcercisable_options: Option<f64>,
    pub unvested_rest_stk: Option<f64>,
    pub salary: Option<f64>,
    pub total_compensation: Option<f64>,
    pub total_bonus: Option<f64>,
    pub cash_bonus: Option<f64>,
    pub dv_of_ann_stock_grant: Option<f64>,
    pub dv_of_ann_option_grant: Option<f64>,
    pub other_comp: Option<f64>,
    pub total_equity_portfolio_less_vos: Option<f64>,
    pub delta_total_compensation: Option<f64>,
    pub cash_bonus_to_salary: Option<f64>,
    pub percentage_ownership: Option<f64>,
    pub total_options: Option<f64>,
    pub equity_pay: Option<f64>,
    pub cash_pay: Option<f64>,
    pub equity_pay_compensation: Option<f64>,
    pub salary_to_compensation: Option<f64>,
    pub cash_bonus_to_compensation: Option<f64>,
    pub directorname: Option<String>,
    pub meanconglomerate_exp: Option<f64>,
    pub sdconglomerate_exp: Option<f64>,
    pub meancount_industries: Option<f64>,
    pub sdcount_industries: Option<f64>,
    pub meanceo_exp_dummy: Option<f64>,
    pub sdceo_exp_dummy: Option<f64>,
    pub meanCountpastpositions: Option<f64>,
    pub sdCountpastpositions: Option<f64>,
    pub meanCountpastfirms: Option<f64>,
    pub sdCountpastfirms: Option<f64>,
    pub conglomerate_exp_z: Option<f64>,
    pub count_industries_z: Option<f64>,
    pub ceo_exp_dummy_z: Option<f64>,
    pub Countpastpositions_z: Option<f64>,
    pub Countpastfirms_z: Option<f64>,
    pub GAI: Option<f64>,
    pub meanGAI: Option<f64>,
    pub sdGAI: Option<f64>,
    pub GAI_z: Option<f64>,
    pub median_GAI_z: Option<f64>,
    pub generalist: Option<f64>,
    pub ivy_league_dummy: Option<f64>,
    pub mba_dummy: Option<f64>,
    pub mkvaltq: Option<f64>,
    pub prccq: Option<f64>,
    pub cshoq: Option<f64>,
    pub dvpspq: Option<f64>,
    pub dvy: Option<f64>,
    pub dvpy: Option<f64>,
    pub mveq: Option<f64>,
    pub div_quarterly: Option<f64>,
    pub div_ytd: Option<f64>,
    pub duplicate1: Option<f64>,
    pub directorid_exec_id: Option<String>,
    pub entityperm: Option<String>,
    pub entityyrqtrperm: Option<String>,
    pub entitycid: Option<String>,
    pub value_of_shares: Option<f64>,
    pub value_of_shares_excl_opts: Option<f64>,
    pub charter_value: Option<f64>,
    pub log_total_compensation: Option<f64>,
    pub total_bonus_to_salary: Option<f64>,
}

impl SurrealCrudModel for FullBankData {
    fn table() -> &'static str {
        "full_bank_data"
    }

    fn id_key(&self) -> Option<String> {
        if let Some(key) = &self.entityyrqtrperm {
            if !key.is_empty() {
                return Some(key.clone());
            }
        }
        match (self.entity, self.year, self.quarter, self.permno, self.companyid) {
            (Some(entity), Some(year), Some(quarter), Some(permno), Some(companyid)) => Some(
                format!(
                    "{entity}:{year}:{quarter}:{permno}:{companyid}",
                    entity = entity,
                    year = year,
                    quarter = quarter,
                    permno = permno,
                    companyid = companyid
                ),
            ),
            _ => None,
        }
    }
}

impl DuckCrudModel for FullBankData {
    fn table() -> &'static str {
        "full_bank_data"
    }

    fn id_key(&self) -> Option<String> {
        <Self as SurrealCrudModel>::id_key(self)
    }
}

impl ToPolars for FullBankData {
    fn schema() -> Schema {
        FullBankData::polars_schema()
    }
}

impl FullBankData {
    pub fn polars_schema() -> Schema {
        macro_rules! f64_field {
            ($name:literal) => {
                Field::new($name.into(), DataType::Float64)
            };
        }
        macro_rules! str_field {
            ($name:literal) => {
                Field::new($name.into(), DataType::String)
            };
        }

        Schema::from_iter(vec![
            f64_field!("year"),
            f64_field!("entity"),
            str_field!("exec_fullname_comp"),
            str_field!("coname"),
            f64_field!("directorid"),
            f64_field!("conglomerate_exp"),
            f64_field!("count_industries"),
            f64_field!("ceo_exp_dummy"),
            f64_field!("Countpastpositions"),
            f64_field!("Countpastfirms"),
            f64_field!("gvkey"),
            f64_field!("companyid"),
            str_field!("titleann"),
            f64_field!("execid"),
            f64_field!("port_delta"),
            f64_field!("port_vega"),
            f64_field!("port_value"),
            f64_field!("shrown_excl_opts"),
            f64_field!("quarter"),
            f64_field!("co_per_rol"),
            str_field!("name"),
            f64_field!("month"),
            f64_field!("day"),
            f64_field!("year_quarter"),
            str_field!("inst_type"),
            f64_field!("LCO"),
            f64_field!("LLP"),
            f64_field!("IntRateSwps_HTM"),
            f64_field!("RWA"),
            f64_field!("Loans"),
            f64_field!("cash"),
            f64_field!("Retained_Earnings"),
            f64_field!("NPL"),
            f64_field!("CL_NPL"),
            f64_field!("MO_NPL"),
            f64_field!("OTHER_NPL"),
            f64_field!("Loangrowth"),
            f64_field!("Ebllp_Loans_t_1"),
            f64_field!("LLP_Loans_t_1"),
            f64_field!("TA"),
            f64_field!("log_TA"),
            f64_field!("TL"),
            f64_field!("TE"),
            f64_field!("Leverage"),
            f64_field!("Tier1Capital"),
            f64_field!("CA"),
            f64_field!("ROA_t_1"),
            f64_field!("ROE_t_1"),
            f64_field!("Loans_TA"),
            f64_field!("Trading_Income_TRA"),
            f64_field!("CL"),
            f64_field!("EBIT"),
            f64_field!("NetIncome"),
            f64_field!("InterestInc"),
            f64_field!("NonInterestInc"),
            f64_field!("OI"),
            f64_field!("NonInterestInc_TA"),
            f64_field!("Trading_Income"),
            f64_field!("DSC"),
            f64_field!("TOTAL_Expenses"),
            f64_field!("Interest_Expenses"),
            f64_field!("Non_Interest_Expenses"),
            f64_field!("Interest_Expenses_TE"),
            f64_field!("Net_InterestInc"),
            f64_field!("Net_NonInterestInc"),
            f64_field!("Net_NonInterestInc_OI"),
            f64_field!("Net_InterestInc_OI"),
            f64_field!("InterestInc_TA"),
            f64_field!("Trading_Assets"),
            f64_field!("Trading_Income_TA"),
            f64_field!("IntRateSwps"),
            f64_field!("IntRateSwps_TA"),
            f64_field!("Income"),
            f64_field!("Trading_Income_TR"),
            f64_field!("Non_Interest_Expenses_TE"),
            f64_field!("fee_mix"),
            f64_field!("rev_mix"),
            f64_field!("InterestInc_Inc"),
            f64_field!("Working_Capital"),
            f64_field!("RetEarnings_TA"),
            f64_field!("EBIT_TA"),
            f64_field!("OI_TA"),
            f64_field!("Working_Capital_TA"),
            f64_field!("Trading_Assets_TA"),
            f64_field!("mismatch"),
            f64_field!("revolver"),
            f64_field!("CILOANS"),
            f64_field!("CONLOANS"),
            f64_field!("TLMI"),
            f64_field!("Forfxfut"),
            f64_field!("ROA"),
            f64_field!("ROE"),
            f64_field!("NII"),
            f64_field!("Other_NIE"),
            f64_field!("Other_IE"),
            f64_field!("Net_Repos"),
            f64_field!("Commercial_Paper"),
            f64_field!("brokered_dep"),
            f64_field!("stdebt"),
            f64_field!("Treas_sec"),
            f64_field!("Net_FedFunds"),
            f64_field!("SubNotesDebt"),
            f64_field!("Other_Debt"),
            f64_field!("htm_tot_secur"),
            f64_field!("htm_tot_secur2"),
            f64_field!("avfs_tot_secur"),
            f64_field!("fv_htm_dom_debt_sec"),
            f64_field!("fv_htm_for_debt_sec"),
            f64_field!("ammor_htm_dom_debt_sec"),
            f64_field!("ammor_htm_for_debt_sec"),
            f64_field!("fv_htm_tot_sec"),
            f64_field!("ammor_htm_tot_sec"),
            f64_field!("htm_tot_secur_TA"),
            f64_field!("htm_tot_secur2_TA"),
            f64_field!("avfs_tot_secur_TA"),
            f64_field!("fv_htm_dom_debt_sec_TA"),
            f64_field!("fv_htm_for_debt_sec_TA"),
            f64_field!("ammor_htm_dom_debt_sec_TA"),
            f64_field!("ammor_htm_for_debt_sec_TA"),
            f64_field!("fv_htm_tot_sec_TA"),
            f64_field!("ammor_htm_tot_sec_TA"),
            f64_field!("MOLOANS"),
            f64_field!("RELOANS"),
            f64_field!("OTHERLOANS"),
            f64_field!("Deposits"),
            f64_field!("GAP12"),
            f64_field!("FCA"),
            f64_field!("FED"),
            f64_field!("FXRD"),
            f64_field!("ERD"),
            f64_field!("CreditPS"),
            f64_field!("CreditPB"),
            f64_field!("NetCreditPB"),
            f64_field!("TotBorrowing"),
            f64_field!("Tier1Capital_Ratio"),
            f64_field!("NPL_Ratio"),
            f64_field!("NonInterestInc_TA_mean_high"),
            f64_field!("NonInterestInc_TA_med_high"),
            f64_field!("NonInterestInc_TA_mean"),
            f64_field!("NonInterestInc_TA_median"),
            f64_field!("InterestInc_TA_mean_high"),
            f64_field!("InterestInc_TA_med_high"),
            f64_field!("InterestInc_TA_mean"),
            f64_field!("InterestInc_TA_median"),
            f64_field!("InterestInc_Inc_mean_high"),
            f64_field!("InterestInc_Inc_med_high"),
            f64_field!("InterestInc_Inc_mean"),
            f64_field!("InterestInc_Inc_median"),
            f64_field!("abs_Delta_ROA_lead"),
            f64_field!("Delta_ROA_lead"),
            f64_field!("Delta_InterestInc_TA_lead"),
            f64_field!("abs_Delta_InterestInc_TA_lead"),
            f64_field!("Delta_NonInterestInc_TA_lead"),
            f64_field!("abs_Delta_NonInterestInc_TA_lead"),
            f64_field!("Deposits_TA"),
            f64_field!("log_Asset_Growth"),
            f64_field!("abs_Delta_ROE_lead"),
            f64_field!("Delta_NPL_Ratio_lead"),
            f64_field!("abs_Delta_NPL_Ratio_lead"),
            f64_field!("Delta_Leverage_lead"),
            f64_field!("abs_Delta_Leverage_lead"),
            f64_field!("Delta_ROE_lead"),
            f64_field!("Delta_LLP_Loans_t_1_lead"),
            f64_field!("abs_Delta_LLP_Loans_t_1_lead"),
            f64_field!("ROA_mean"),
            f64_field!("ROA_median"),
            f64_field!("ROA_mean_high"),
            f64_field!("ROA_med_high"),
            f64_field!("ROE_mean"),
            f64_field!("ROE_median"),
            f64_field!("ROE_mean_high"),
            f64_field!("ROE_med_high"),
            f64_field!("TA_mean"),
            f64_field!("TA_median"),
            f64_field!("TA_mean_high"),
            f64_field!("TA_med_high"),
            f64_field!("fee_mix_mean"),
            f64_field!("fee_mix_median"),
            f64_field!("fee_mix_mean_high"),
            f64_field!("fee_mix_med_high"),
            f64_field!("rev_mix_mean"),
            f64_field!("rev_mix_median"),
            f64_field!("rev_mix_mean_high"),
            f64_field!("rev_mix_med_high"),
            f64_field!("Deposits_TA_mean"),
            f64_field!("Deposits_TA_median"),
            f64_field!("Deposits_TA_mean_high"),
            f64_field!("Deposits_TA_med_high"),
            f64_field!("log_Asset_Growth_mean"),
            f64_field!("log_Asset_Growth_median"),
            f64_field!("log_Asset_Growth_mean_high"),
            f64_field!("log_Asset_Growth_med_high"),
            f64_field!("RWA_TA"),
            f64_field!("Trading_Assets_TA_mean_high"),
            f64_field!("Trading_Assets_TA_med_high"),
            f64_field!("Trading_Assets_TA_mean"),
            f64_field!("Trading_Assets_TA_median"),
            f64_field!("Trading_Assets_Dummy"),
            f64_field!("Trading_Income_TA_mean_high"),
            f64_field!("Trading_Income_TA_med_high"),
            f64_field!("Trading_Income_TA_mean"),
            f64_field!("Trading_Income_TA_median"),
            f64_field!("Trading_Income_TR_mean_high"),
            f64_field!("Trading_Income_TR_med_high"),
            f64_field!("Trading_Income_TR_mean"),
            f64_field!("Trading_Income_TR_median"),
            f64_field!("Trading_Income_TRA_mean_high"),
            f64_field!("Trading_Income_TRA_med_high"),
            f64_field!("Trading_Income_TRA_mean"),
            f64_field!("Trading_Income_TRA_median"),
            f64_field!("abs_Delta_Loans_lead"),
            f64_field!("Delta_Loans_lead"),
            f64_field!("abs_Delta_Loans_lead_perc"),
            f64_field!("Delta_Loans_lead_perc"),
            f64_field!("abs_Delta_Deposits_lead"),
            f64_field!("Delta_Deposits_lead"),
            f64_field!("abs_Delta_Deposits_lead_perc"),
            f64_field!("Delta_Deposits_lead_perc"),
            f64_field!("abs_Delta_htm_tot_secur_lead"),
            f64_field!("Delta_htm_tot_secur_lead"),
            f64_field!("abs_Delta_htm_tot_secur_perc"),
            f64_field!("Delta_htm_tot_secur_lead_perc"),
            f64_field!("states_counts"),
            f64_field!("interstate_bank"),
            f64_field!("permco"),
            f64_field!("permno"),
            f64_field!("total_return"),
            f64_field!("adj_total_return"),
            str_field!("conm"),
            str_field!("shrcls"),
            f64_field!("vwretd_VAR1_yr"),
            f64_field!("ewretd_VAR1_yr"),
            f64_field!("vwretd_VAR5_yr"),
            f64_field!("ewretd_VAR5_yr"),
            f64_field!("vwretd_VAR1_qtr"),
            f64_field!("ewretd_VAR1_qtr"),
            f64_field!("vwretd_VAR5_qtr"),
            f64_field!("ewretd_VAR5_qtr"),
            f64_field!("ES1_ew_yr"),
            f64_field!("ES5_ew_yr"),
            f64_field!("ES1_ew_yr_t_1"),
            f64_field!("delta_ES1_ew_yr_lag"),
            f64_field!("delta_ES1_ew_yr_lead"),
            f64_field!("ES5_ew_yr_t_1"),
            f64_field!("delta_ES5_ew_yr_lag"),
            f64_field!("delta_ES5_ew_yr_lead"),
            f64_field!("vwretd_MES1_ew_yr"),
            f64_field!("ewretd_MES1_ew_yr"),
            f64_field!("vwretd_MES5_ew_yr"),
            f64_field!("ewretd_MES5_ew_yr"),
            f64_field!("vwretd_MES1_ew_yr_t_1"),
            f64_field!("delta_vwretd_MES1_ew_yr_lag"),
            f64_field!("delta_vwretd_MES1_ew_yr_lead"),
            f64_field!("ewretd_MES1_ew_yr_t_1"),
            f64_field!("delta_ewretd_MES1_ew_yr_lag"),
            f64_field!("delta_ewretd_MES1_ew_yr_lead"),
            f64_field!("vwretd_MES5_ew_yr_t_1"),
            f64_field!("delta_vwretd_MES5_ew_yr_lag"),
            f64_field!("delta_vwretd_MES5_ew_yr_lead"),
            f64_field!("ewretd_MES5_ew_yr_t_1"),
            f64_field!("delta_ewretd_MES5_ew_yr_lag"),
            f64_field!("delta_ewretd_MES5_ew_yr_lead"),
            f64_field!("ES1_ew_qtr"),
            f64_field!("ES5_ew_qtr"),
            f64_field!("ES1_ew_qtr_t_1"),
            f64_field!("ES1_ew_qtr_tp_1"),
            f64_field!("delta_ES1_ew_qtr_lag"),
            f64_field!("delta_ES1_ew_qtr_lead"),
            f64_field!("ES5_ew_qtr_t_1"),
            f64_field!("ES5_ew_qtr_tp_1"),
            f64_field!("delta_ES5_ew_qtr_lag"),
            f64_field!("delta_ES5_ew_qtr_lead"),
            f64_field!("vwretd_MES1_ew_qtr"),
            f64_field!("ewretd_MES1_ew_qtr"),
            f64_field!("vwretd_MES5_ew_qtr"),
            f64_field!("ewretd_MES5_ew_qtr"),
            f64_field!("vwretd_MES1_ew_qtr_t_1"),
            f64_field!("vwretd_MES1_ew_qtr_tp_1"),
            f64_field!("delta_vwretd_MES1_ew_qtr_lag"),
            f64_field!("delta_vwretd_MES1_ew_qtr_lead"),
            f64_field!("ewretd_MES1_ew_qtr_t_1"),
            f64_field!("ewretd_MES1_ew_qtr_tp_1"),
            f64_field!("delta_ewretd_MES1_ew_qtr_lag"),
            f64_field!("delta_ewretd_MES1_ew_qtr_lead"),
            f64_field!("vwretd_MES5_ew_qtr_t_1"),
            f64_field!("vwretd_MES5_ew_qtr_tp_1"),
            f64_field!("delta_vwretd_MES5_ew_qtr_lag"),
            f64_field!("delta_vwretd_MES5_ew_qtr_lead"),
            f64_field!("ewretd_MES5_ew_qtr_t_1"),
            f64_field!("ewretd_MES5_ew_qtr_tp_1"),
            f64_field!("delta_ewretd_MES5_ew_qtr_lag"),
            f64_field!("delta_ewretd_MES5_ew_qtr_lead"),
            f64_field!("sd_ret_q"),
            f64_field!("sd_ret_q_t_1"),
            f64_field!("sd_ret_q_tp_1"),
            f64_field!("delta_sd_ret_q_lag"),
            f64_field!("delta_sd_ret_q_lead"),
            f64_field!("sd_ret_yr"),
            f64_field!("sd_ret_yr_t_1"),
            f64_field!("delta_sd_ret_yr_lag"),
            f64_field!("delta_sd_ret_yr_lead"),
            str_field!("ceoann"),
            f64_field!("age"),
            f64_field!("tdc1"),
            f64_field!("bonus"),
            f64_field!("noneq_incent"),
            f64_field!("option_awards"),
            f64_field!("rstkgrnt"),
            f64_field!("othcomp"),
            f64_field!("shrown_tot"),
            f64_field!("opt_unex_exer_est_val"),
            f64_field!("opt_exer_val"),
            f64_field!("option_awards_blk_value"),
            f64_field!("opt_unex_unexer_est_val"),
            f64_field!("stock_unvest_val"),
            f64_field!("shares_owned"),
            f64_field!("excercisable_options"),
            f64_field!("unexcercisable_options"),
            f64_field!("unvested_rest_stk"),
            f64_field!("salary"),
            f64_field!("total_compensation"),
            f64_field!("total_bonus"),
            f64_field!("cash_bonus"),
            f64_field!("dv_of_ann_stock_grant"),
            f64_field!("dv_of_ann_option_grant"),
            f64_field!("other_comp"),
            f64_field!("total_equity_portfolio_less_vos"),
            f64_field!("delta_total_compensation"),
            f64_field!("cash_bonus_to_salary"),
            f64_field!("percentage_ownership"),
            f64_field!("total_options"),
            f64_field!("equity_pay"),
            f64_field!("cash_pay"),
            f64_field!("equity_pay_compensation"),
            f64_field!("salary_to_compensation"),
            f64_field!("cash_bonus_to_compensation"),
            str_field!("directorname"),
            f64_field!("meanconglomerate_exp"),
            f64_field!("sdconglomerate_exp"),
            f64_field!("meancount_industries"),
            f64_field!("sdcount_industries"),
            f64_field!("meanceo_exp_dummy"),
            f64_field!("sdceo_exp_dummy"),
            f64_field!("meanCountpastpositions"),
            f64_field!("sdCountpastpositions"),
            f64_field!("meanCountpastfirms"),
            f64_field!("sdCountpastfirms"),
            f64_field!("conglomerate_exp_z"),
            f64_field!("count_industries_z"),
            f64_field!("ceo_exp_dummy_z"),
            f64_field!("Countpastpositions_z"),
            f64_field!("Countpastfirms_z"),
            f64_field!("GAI"),
            f64_field!("meanGAI"),
            f64_field!("sdGAI"),
            f64_field!("GAI_z"),
            f64_field!("median_GAI_z"),
            f64_field!("generalist"),
            f64_field!("ivy_league_dummy"),
            f64_field!("mba_dummy"),
            f64_field!("mkvaltq"),
            f64_field!("prccq"),
            f64_field!("cshoq"),
            f64_field!("dvpspq"),
            f64_field!("dvy"),
            f64_field!("dvpy"),
            f64_field!("mveq"),
            f64_field!("div_quarterly"),
            f64_field!("div_ytd"),
            f64_field!("duplicate1"),
            str_field!("directorid_exec_id"),
            str_field!("entityperm"),
            str_field!("entityyrqtrperm"),
            str_field!("entitycid"),
            f64_field!("value_of_shares"),
            f64_field!("value_of_shares_excl_opts"),
            f64_field!("charter_value"),
            f64_field!("log_total_compensation"),
            f64_field!("total_bonus_to_salary"),
        ])
    }

    pub async fn duck_from_parquet(
        conn: Arc<Mutex<Connection>>,
        parquet_path: impl AsRef<Path>,
    ) -> Result<usize, AppError> {
        <Self as DuckCrudModel>::upsert_from_parquet_one_file(
            conn,
            parquet_path,
            None,
            Some(<Self as DuckCrudModel>::table().into()),
        )
        .await
    }
}

