library(arrow)
setwd("/home/yakaman/Dropbox/Desktop/tesero-sol/software_development/trading/data/")
df_daily = read_parquet("raw_files/parquet/crsp/us_bhc/daily_usbank_crsp.parquet")
df_monthly = read_parquet("raw_files/parquet/crsp/us_bhc/monthly_usbank_crsp.parquet")
df_link = read_parquet("raw_files/parquet/bank_regulatory/bhck_crsp_link/bhck_crsp_link_file.parquet")
colnames(df_daily) <- tolower(colnames(df_daily))
colnames(df_monthly) <- tolower(colnames(df_monthly))
colnames(df_link) <- tolower(colnames(df_link))
names(df_daily) <- tolower(names(df_daily))
names(df_monthly) <- tolower(names(df_monthly))
names(df_link) <- tolower(names(df_link))
print("structure crsp daily:")
str(df_daily)
print("structure crsp monthly:")
str(df_monthly)
print("structure bhck crsp link:")
str(df_link)
write_parquet(df_daily, "raw_files/parquet/crsp/us_bhc/daily_usbank_crsp.parquet")
write_parquet(df_monthly, "raw_files/parquet/crsp/us_bhc/monthly_usbank_crsp.parquet")
write_parquet(df_link, "raw_files/parquet/bank_regulatory/bhck_crsp_link/bhck_crsp_link_file.parquet")
rm(list=ls())