setwd("/home/yakaman/Dropbox/Desktop/tesero-sol/software_development/trading/words_db/scripts/")
source("save_parquet.r")
source("unzip_zip_files.r")
source("unzip_and_convert_to_parquet.r")
setwd("/home/yakaman/Dropbox/Desktop/tesero-sol/software_development/trading/data/")
convert_zip_csvs_to_parquet_zip("zip/crsp/us_bhc/","zip/crsp/us_bhc/")
#convert_zip_csvs_to_parquet_zip("zip/bank_regulatory/bhck_crsp_link/","zip/bank_regulatory/bhck_crsp_link/")
#convert_zip_csvs_to_parquet_zip("zip/compustat/execucomp/anncomp/","zip/compustat/execucomp/anncomp/")
#convert_zip_csvs_to_parquet_zip("zip/compustat/execucomp/defferedcomp/","zip/compustat/execucomp/defferedcomp/")
#convert_zip_csvs_to_parquet_zip("zip/compustat/execucomp/ltawdtab/","zip/compustat/execucomp/ltawdtab/")
#convert_zip_csvs_to_parquet_zip("zip/compustat/execucomp/outstandingawards/","zip/compustat/execucomp/outstandingawards/")
#convert_zip_csvs_to_parquet_zip("zip/compustat/execucomp/pension/","zip/compustat/execucomp/pension/")
#convert_zip_csvs_to_parquet_zip("zip/compustat/execucomp/planbasedawards/","zip/compustat/execucomp/planbasedawards/")
#convert_zip_csvs_to_parquet_zip("zip/compustat/execucomp/stgrttab/","zip/compustat/execucomp/stgrttab/")
#convert_zip_csvs_to_parquet_zip("zip/factors/global/monthly/","zip/factors/global/monthly/")
#convert_zip_csvs_to_parquet_zip("zip/bank_regulatory/holding_company_financials/bhck_series1","zip/bank_regulatory/holding_company_financials/bhck_series1")
#convert_zip_csvs_to_parquet_zip("zip/bank_regulatory/holding_company_financials/bhck_series2","zip/bank_regulatory/holding_company_financials/bhck_series2")
#convert_zip_csvs_to_parquet_zip("zip/bank_regulatory/holding_company_financials/bhck_other","zip/bank_regulatory/holding_company_financials/bhck_other")
#convert_zip_csvs_to_parquet_zip("zip/bank_regulatory/holding_company_financials/bhck_legacy","zip/bank_regulatory/holding_company_financials/bhck_legacy")
#convert_zip_csvs_to_parquet_zip("zip/compustat/global_securities/monthly","zip/compustat/global_securities/monthly")
#convert_zip_csvs_to_parquet_zip("zip/factors/us/daily","zip/factors/us/daily")
#convert_zip_csvs_to_parquet_zip("zip/factors/us/monthly","zip/factors/us/monthly")
#convert_zip_csvs_to_parquet_zip("zip/crsp_ciz_sample/market_index/monthly","zip/crsp_ciz_sample/market_index/monthly")
#convert_zip_csvs_to_parquet_zip("zip/crsp_ciz_sample/stkmthlysecuritydata/","zip/crsp_ciz_sample/stkmthlysecuritydata/")
#convert_zip_csvs_to_parquet_zip("zip/compustat/world_indicators/","zip/compustat/world_indicators/")
#convert_zip_csvs_to_parquet_zip("zip/compustat/global_fundamentals","zip/compustat/global_fundamentals")# "raw_files/parqueut/compustat/global_fundamentals")
#convert_zip_csvs_to_parquet_zip("zip/compustat/global_names","zip/compustat/global_names")# "raw_files/parqueut/compustat/global_names")
unzip_zip_files(input_dir="zip/crsp/us_bhc/", output_dir="raw_files/parquet/crsp/us_bhc/",match_regex=".zip$", limit=40, create_subdir_per_zip = FALSE,overwrite=TRUE, name_from_zip=TRUE,  add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/bank_regulatory/bhck_crsp_link/", output_dir="raw_files/parquet/bank_regulatory/bhck_crsp_link/",match_regex=".zip$", limit=40, create_subdir_per_zip = FALSE,overwrite=TRUE, name_from_zip=TRUE,  add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/compustat/execucomp/anncomp/", output_dir="raw_files/parquet/compustat/execucomp/anncomp/",match_regex=".zip$", limit=40, create_subdir_per_zip = FALSE,overwrite=TRUE, name_from_zip=TRUE,  add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/compustat/execucomp/defferedcomp/", output_dir="raw_files/parquet/compustat/execucomp/deferredcomp/",match_regex=".zip$", limit=40, create_subdir_per_zip = FALSE,overwrite=TRUE, name_from_zip=TRUE,  add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/compustat/execucomp/ltawdtab/", output_dir="raw_files/parquet/compustat/execucomp/ltawdtab/",match_regex=".zip$", limit=40, create_subdir_per_zip = FALSE,overwrite=TRUE, name_from_zip=TRUE,  add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/compustat/execucomp/outstandingawards/", output_dir="raw_files/parquet/compustat/execucomp/outstandingawards/",match_regex=".zip$", limit=40, create_subdir_per_zip = FALSE,overwrite=TRUE, name_from_zip=TRUE,  add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/compustat/execucomp/pension/", output_dir="raw_files/parquet/compustat/execucomp/pension/",match_regex=".zip$", limit=40, create_subdir_per_zip = FALSE,overwrite=TRUE, name_from_zip=TRUE,  add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/compustat/execucomp/planbasedawards/", output_dir="raw_files/parquet/compustat/execucomp/planbasedawards/",match_regex=".zip$", limit=40, create_subdir_per_zip = FALSE,overwrite=TRUE, name_from_zip=TRUE,  add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/compustat/execucomp/stgrttab/", output_dir="raw_files/parquet/compustat/execucomp/stgrttab/",match_regex=".zip$", limit=40, create_subdir_per_zip = FALSE,overwrite=TRUE, name_from_zip=TRUE,  add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/factors/global/monthly/", output_dir="raw_files/parquet/factors/global/monthly/", match_regex=".zip$", limit=10, create_subdir_per_zip=FALSE, overwrite=TRUE, name_from_zip=TRUE, add_extension=".parquet")
#unzip_zip_files(input_dir="zip/bank_regulatory/holding_company_financials/bhck_series1", output_dir="raw_files/parquet/bank_regulatory/holding_company_financials/bhck_series1", match_regex=".zip$", limit=10, create_subdir_per_zip = FALSE, overwrite=TRUE, add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/bank_regulatory/holding_company_financials/bhck_series2", output_dir="raw_files/parquet/bank_regulatory/holding_company_financials/bhck_series2", match_regex=".zip$", limit=10, create_subdir_per_zip = FALSE, overwrite=TRUE, add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/bank_regulatory/holding_company_financials/bhck_other", output_dir="raw_files/parquet/bank_regulatory/holding_company_financials/bhck_other", match_regex=".zip$", limit=10, create_subdir_per_zip = FALSE, overwrite=TRUE, add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/bank_regulatory/holding_company_financials/bhck_legacy", output_dir="raw_files/parquet/bank_regulatory/holding_company_financials/bhck_legacy", match_regex=".zip$", limit=10, create_subdir_per_zip = FALSE, overwrite=TRUE, add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/factors/us/daily", output_dir="raw_files/parquet/factors/us/daily", match_regex=".zip$", limit=10, create_subdir_per_zip = FALSE, overwrite=TRUE, add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/factors/us/monthly", output_dir="raw_files/parquet/factors/us/monthly", match_regex=".zip$", limit=10, create_subdir_per_zip = FALSE, overwrite=TRUE, add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/crsp_ciz_sample/market_index/monthly", output_dir="raw_files/parquet/crsp_ciz_sample/market_index/monthly", match_regex=".zip$", limit=10, create_subdir_per_zip = FALSE, overwrite=TRUE, add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/crsp_ciz_sample/stkmthlysecuritydata/", output_dir="raw_files/parquet/crsp_ciz_sample/stkmthlysecuritydata/", match_regex=".zip$", limit=100, create_subdir_per_zip = FALSE, overwrite=TRUE, name_from_zip=TRUE, add_extension = ".parquet")
# unzip_zip_files(input_dir="zip/crsp_ciz_sample/stkdlysecuritydata/", output_dir="raw_files/parquet/crsp_ciz_sample/stkdlysecuritydata/", match_regex=".zip$", limit=100, create_subdir_per_zip = FALSE, overwrite=TRUE, name_from_zip=TRUE, add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/compustat/world_indicators/", output_dir="raw_files/parquet/compustat/world_indicators/", match_regex=".zip$", limit=10, create_subdir_per_zip = FALSE, overwrite=TRUE, add_extension = ".parquet")
#unzip_zip_files(input_dir="zip/compustat/global_names", output_dir="raw_files/parquet/compustat/global_names", match_regex=".zip$", limit=10, create_subdir_per_zip = FALSE, overwrite=TRUE, add_extension = ".parquet")
# unzip_zip_files(input_dir="zip/compustat/global_fundamentals/", output_dir="raw_files/parquet/compustat/global_fundamentals/",match_regex=".zip$", limit=40, create_subdir_per_zip = FALSE,overwrite=TRUE, name_from_zip=TRUE,  add_extension = ".parquet")
# unzip_zip_files(input_dir="zip/compustat/global_securities/monthly/", output_dir="raw_files/parquet/compustat/global_securities/monthly/", match_regex=".zip$", limit=100, create_subdir_per_zip = FALSE, overwrite=TRUE, name_from_zip=TRUE, add_extension = ".parquet")
# unzip_zip_files(  input_dir="zip/compustat/global_securities/daily/", output_dir="raw_files/parquet/compustat/global_securities/daily",  match_regex=".zip$", limit=100, create_subdir_per_zip = FALSE, overwrite=TRUE, name_from_zip=TRUE, add_extension = ".parquet")